{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "devops-chart.fullname" . }}-ingress
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "devops-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.containerPort }}
{{- end }}
