replicaCount: 1

image:
  repository: pramu55/devops-app
  tag: v1
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

containerPort: 3000

probes:
  path: /health
  readinessInitialDelaySeconds: 5
  readinessPeriodSeconds: 10
  livenessInitialDelaySeconds: 15
  livenessPeriodSeconds: 20
